name: Build and Deploy Tickets App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./tickets

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Compilar con Maven (Clean and Install)
        run: mvn clean install

      - name: Perform Security Scan
        uses: ShiftLeftSecurity/scan-action@master
        with:
          type: "credscan,java,depscan"

      - uses: actions/upload-artifact@v4
        with:
          name: reports
          path: reports

      - name: Remove target directory
        run: sudo rm -rf target/*

      - name: Maven clean
        run: mvn clean

      - name: Build with Maven
        run: mvn -X package --file pom.xml

      - name: Upload JAR file
        uses: actions/upload-artifact@v4
        with:
          name: springboot-tickets-api.jar
          path: target/springboot-tickets-api.jar

      - name: List target directory contents
        run: ls -l target
